version: '3'

networks:
    laravel_network:
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
        environment:
            - APP_ENV=local
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=packiyo
            - DB_USERNAME=root
            - DB_PASSWORD=775522
        depends_on:
            - db
        networks:
            - laravel_network

    db:
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: packiyo
            MYSQL_USER: packiyo
            MYSQL_PASSWORD: '775522'
            MYSQL_ROOT_PASSWORD: '123456'
        ports:
            - "3307:3306"
        networks:
            - laravel_network
